version: "3.8"
services:
    marketplace:
        build:
            context: .
            dockerfile: marketplace/dockerfile
        environment:
            RECOMMENDATIONS_HOST: recommendations
        image: marketplace
        networks:
            - microservices
        ports:
            - 5000:5000


    recommendations:
        build:
            context: .
            dockerfile: recommendations/dockerfile
        image: recommendations
        networks:
            - microservices
networks:
    microservices: